# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snip.proto',
  package='snip',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nsnip.proto\x12\x04snip\"\x1a\n\x0bSnipRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1b\n\x0cSnipResponse\x12\x0b\n\x03url\x18\x01 \x01(\t2D\n\x0eUrlSnipService\x12\x32\n\x07snip_it\x12\x11.snip.SnipRequest\x1a\x12.snip.SnipResponse\"\x00\x62\x06proto3')
)




_SNIPREQUEST = _descriptor.Descriptor(
  name='SnipRequest',
  full_name='snip.SnipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='snip.SnipRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=46,
)


_SNIPRESPONSE = _descriptor.Descriptor(
  name='SnipResponse',
  full_name='snip.SnipResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='snip.SnipResponse.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['SnipRequest'] = _SNIPREQUEST
DESCRIPTOR.message_types_by_name['SnipResponse'] = _SNIPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SnipRequest = _reflection.GeneratedProtocolMessageType('SnipRequest', (_message.Message,), dict(
  DESCRIPTOR = _SNIPREQUEST,
  __module__ = 'snip_pb2'
  # @@protoc_insertion_point(class_scope:snip.SnipRequest)
  ))
_sym_db.RegisterMessage(SnipRequest)

SnipResponse = _reflection.GeneratedProtocolMessageType('SnipResponse', (_message.Message,), dict(
  DESCRIPTOR = _SNIPRESPONSE,
  __module__ = 'snip_pb2'
  # @@protoc_insertion_point(class_scope:snip.SnipResponse)
  ))
_sym_db.RegisterMessage(SnipResponse)



_URLSNIPSERVICE = _descriptor.ServiceDescriptor(
  name='UrlSnipService',
  full_name='snip.UrlSnipService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=77,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='snip_it',
    full_name='snip.UrlSnipService.snip_it',
    index=0,
    containing_service=None,
    input_type=_SNIPREQUEST,
    output_type=_SNIPRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_URLSNIPSERVICE)

DESCRIPTOR.services_by_name['UrlSnipService'] = _URLSNIPSERVICE

# @@protoc_insertion_point(module_scope)
