# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.snip_pb2 as snip__pb2


class UrlSnipServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.snip_it = channel.unary_unary(
        '/snip.UrlSnipService/snip_it',
        request_serializer=snip__pb2.SnipRequest.SerializeToString,
        response_deserializer=snip__pb2.SnipResponse.FromString,
        )


class UrlSnipServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def snip_it(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UrlSnipServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'snip_it': grpc.unary_unary_rpc_method_handler(
          servicer.snip_it,
          request_deserializer=snip__pb2.SnipRequest.FromString,
          response_serializer=snip__pb2.SnipResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'snip.UrlSnipService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
